### ISSUE TITLE
Wrong redirect status code

### ISSUE THREAD

**Issue by Yurasb** [v1-wizard/url_shortener#4]
Test:
>def test_redirect_status_code(purge_all_links, create_shortcut_link):

>    purge_all_links
>    create_shortcut_link

>    response = request(method='GET', url='http://localhost:8888/r/{}'.format(create_shortcut_link.json(['id']))

>    assert response.status_code == 302

Error:
>       assert response.status_code == 302
>E       assert 200 == 302
>E        +  where 200 = <Response [200]>.status_code

**Comment by Yurasb** [comment]
Also, bound method of requests lib is_redirected returns False:
>       assert response.is_redirect
>E       assert False
>E        +  where False = <Response [200]>.is_redirect

**Comment by v1-wizard** [comment]
It's expected behavior. You should use flag `allow_redirects=False` with requests lib.
