### ISSUE TITLE
No link validation

### ISSUE THREAD

**Issue by Yurasb** [v1-wizard/url_shortener#5]
Shortcut service processes request with invalid link and respond with status 200 OK:
>def test_shortcut_invalid_link():
>        response = request(method='POST', url='http://localhost:8888/shortcut', data='{ "link": "github.com/Yurasb/url_shortener_testing"}')

>       assert response.status_code == 400
>E       assert 200 == 400
>E        +  where 200 = <Response [200]>.status_code

**Comment by v1-wizard** [comment]
Fixed in 390ef17bccdbef7b504570df27a57e0d9003d9bb.
